name: Test Re-Usable

on:
  workflow_call:
    inputs:
      source:
        description: 'Source'
        required: true
        type: string
        default: 'test_application'

jobs:
  test_application:
    runs-on: ubuntu-latest
    steps:
      - name: Test Application 
        run: |
          RANDOM_NUMBER=$(python -c "import random; print(random.random())")
          echo "Generated random number is $RANDOM_NUMBER"
          if (( $(echo "$RANDOM_NUMBER < 0.5" | bc -l) )); then
            echo "Failing the step"
            exit 1
          fi
      - name:  Output Source
        run: |
          echo "Source is ${{ github.event.inputs.source }}"
