name: Test 

on:
  workflow_dispatch:

jobs:
  test_application:
    steps:
      - name: Test Application 
        run: |
          RANDOM_NUMBER=$(python -c "import random; print(random.random())")
          echo "Generated random number is $RANDOM_NUMBER"
          if (( $(echo "$RANDOM_NUMBER < 0.5" | bc -l) )); then
            echo "Failing the step"
            exit 1
          fi